// Wall manifest. Data (src/title/author) is generated by
// scripts/fetch-onboarding-covers.mjs; this module adds the editorial
// bits: which books are "hero" (they flip to a spine and cross the
// screen on exit) and how the covers are dealt into columns.

import data from "./covers.data.json";

// Titles that read well on a thin vertical spine.
const HERO_TITLES = new Set(["Circe", "The Road", "Piranesi"]);

export const COVERS = data.map((c, i) => ({
  id: i,
  src: c.src,
  title: c.title,
  author: c.author,
  hero: HERO_TITLES.has(c.title),
}));

export const HERO_COVERS = COVERS.filter((c) => c.hero);

export const COLUMN_COUNT = 5;

// Deal covers round-robin into columns, repeating the deck if there
// aren't enough to fill every column to `perColumn`.
export function columns(perColumn = 8) {
  const cols = Array.from({ length: COLUMN_COUNT }, () => []);
  let d = 0;
  for (let row = 0; row < perColumn; row += 1) {
    for (let col = 0; col < COLUMN_COUNT; col += 1) {
      cols[col].push(COVERS[d % COVERS.length]);
      d += 1;
    }
  }
  return cols;
}
